### ISSUE TITLE
Update database for Topics to have a boolean field for resolved 

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#10]
Create a new field for new topics that is a boolean indicating whether or not the topic has been resolved. Should be false on default. May be able to do this by just adding a new field to topic data, since redis is not a relational database. Sprint 1
Relevant file: src/topics/create.js
@Noor-5 
Acceptance Criteria: successfully create new posts with the default resolved status. Check that a new post has the resolved field.
Estimated effort: 1 -2 hours

**Comment by gonzalezjo** [comment]
Resolved in some sense #19
