### ISSUE TITLE
API endpoint to call resolved functionality

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#12]
Create an API that calls functions in the topics/resolve.js module and updates the topic.
@Noor-5 
Relavent File:
src/api/topics.js
src/toics/tools.js

Acceptance criteria: Test the function in topics/tools.js that toggles resolve.

Dependent on #10, #11

Estimated Effort: 4-5 hours

**Comment by gonzalezjo** [comment]
Ended up being unneeded.
