### ISSUE TITLE
API route to update resolved field

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#13]
Create a new puts API route to update the resolved field.
@Noor-5 
src/routes/write/topics.js

Acceptance criteria: Call endpoint to toggle resolved status and view json output to confirm whether the change was made.

Estimated Effort: 1 - 2 hours

Dependent on #10, #11, #12

**Comment by gonzalezjo** [comment]
Resolved by #19
