### ISSUE TITLE
Display resolved status in topics index and in topics show

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#16]
Show the resolve status for each topic in the list and in the page for a specific topic.
Relavent file:
themes/templates/partials/topics_list.tpl

Acceptance Criteria: Text for each row in the list indicating resolved status. Text somewhere in the show screen for a topic indicating the correct status.

Dependent on #10

**Comment by gonzalezjo** [comment]
Resolved.
