### ISSUE TITLE
Create a toggle button for resolve status

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#17]
UI feature for users to toggle the resolved status of a post.
@Noor-5 
Relavent files:
themes/templates/partials/topic/topic-menu-list.tpl
public/language/en-us/topics.json
themes/templates/topic.tpl

Acceptance Criteria: basic functionality to toggle resolved status and refresh the display

Dependent on #13 

Estimated 2-3 hours

**Comment by gonzalezjo** [comment]
Resolved by #27
