### ISSUE TITLE
Change authorization so that only people with correct permissions can view the toggle resolve button

### ISSUE THREAD

**Issue by Noor-5** [CMU-313/fall23-nodebb-code-crafters#28]
Only the original poster of a topic and the admins/instructors should be able to toggle the resolve status of a post.

Medium effort: wrap the button in a conditional on the user role. Write any necessary functions to check user role. post_bar.tpl

Medium Impact: minimize user frustration in seeing a button they don't have the permission to click.

**Comment by gonzalezjo** [comment]
Resolved in #27
